# SKLEARN IMPUTER : NETTOYAGE DE DONNÉES


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.linear_model import SGDClassifier

## SimpleImputer 

In [3]:
from sklearn.impute import SimpleImputer

In [4]:
X = np.array([[10,3],
             [0,4],
             [5,3],
             [np.nan,3]])

In [7]:
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')

imputer.fit_transform(X)

array([[10.,  3.],
       [ 0.,  4.],
       [ 5.,  3.],
       [ 5.,  3.]])

In [8]:
X_test = np.array([[12,5],
                   [40,2],
                   [5,5],
                   [np.nan,np.nan]])

imputer.transform(X_test)

array([[12.  ,  5.  ],
       [40.  ,  2.  ],
       [ 5.  ,  5.  ],
       [ 5.  ,  3.25]])

# ------------------------------------------------------------------------------------------------------

## KNNImputer

In [3]:
#from sklearn.impute import KNNImputer
from sklearn.impute import 

ImportError: cannot import name KNNImputer

In [1]:
!pip install --upgrade scikit-learn

Requirement already up-to-date: scikit-learn in c:\users\user.user-pc\anaconda2\lib\site-packages (0.20.4)


DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.


In [ ]:
from sklearn.impute import K

In [4]:
pip install PyHamcrest>=1.9.0 argparse>=1.1

SyntaxError: invalid syntax (<ipython-input-4-1e042f359e2c>, line 1)

In [11]:

#imputer = KNNImputer(n-neighbors=1)

#imputer.fit_transform(X)

# ------------------------------------------------------------------------------------------------------

## MissingIndicator

In [12]:
from sklearn.impute import MissingIndicator
from sklearn.pipeline import make_union

In [13]:
X = np.array([[1,100],
             [2,30],
             [3,15],
             [np.nan,np.nan]])

In [14]:
MissingIndicator().fit_transform(X)

array([[False, False],
       [False, False],
       [False, False],
       [ True,  True]])

In [16]:
pipeline = make_union(SimpleImputer(strategy='constant',fill_value=-99 ), MissingIndicator())

pipeline.fit_transform(X)

array([[  1., 100.,   0.,   0.],
       [  2.,  30.,   0.,   0.],
       [  3.,  15.,   0.,   0.],
       [-99., -99.,   1.,   1.]])

# ------------------------------------------------------------------------------------------------------

## Application

In [18]:
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
import seaborn as sns 

In [19]:
titanic = sns.load_dataset('titanic')
X = titanic[['pclass','age']]
y = titanic['survived']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=5)